/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rabbitmq.showCase;

import com.rabbitmq.client.*;

import javax.net.ssl.SSLContext;

public class SaslApp
{

    private static String queueName = "java-sasl-queues";
    private static String username  = "gregoryg-a01.vmware.com";

    public static void main(String[] args)
    {
        String vhost = "/";

        try {
            ConnectionFactory factory = new ConnectionFactory();
            factory.setHost("localhost");
            factory.setPort(5671);
            factory.setVirtualHost(vhost);
            factory.setUsername(username);
            factory.setPassword("");

            SSLContext context = SSLContext.getDefault();
            factory.useSslProtocol(context);
            factory.setSaslConfig(DefaultSaslConfig.EXTERNAL);

//            factory.useSslProtocol();

            Connection conn = factory.newConnection();
            Channel channel = conn.createChannel();

            // non-durable, exclusive, auto-delete queue
            channel.queueDeclare(queueName, false, true, true, null);
            channel.basicPublish("", queueName, null, "Hello, World".getBytes());

            GetResponse chResponse = channel.basicGet(queueName, false);
            if (chResponse == null) {
                System.out.println("No message retrieved");
            } else {
                byte[] body = chResponse.getBody();
                System.out.println("Received: " + new String(body));
            }

            channel.close();
            conn.close();
        }
        catch (Exception e) {
            e.printStackTrace();
        }

    }
}
